import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hiking Web",
  description: "Generated by MS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#e1e6ea]`}>
        <div className="max-w-[90%] mx-auto">
          <Navbar/>
        {children}
        <Footer/>
        </div>
        </body>
    </html>
  );
}
